spring:  
  datasource: 
    url: jdbc:mysql://localhost:3306/disney?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false 
  mvc:
      pathmatch:
            matching-strategy: ant-path-matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: registromailalkemy@gmail.com
    password: alkemy.123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required : true
            enable: true
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes:
      - cookie
   

